### ISSUE TITLE
setenv.sh ENV_VARS includes all stdout

### ISSUE THREAD

**Issue by marloeuyjr** [envio-cli/envio#27]
**Describe the bug**
setenv.sh set ENV_VARS by running `envio list -n dev -v`.
This includes unnecessary stdout print messages like:
```
New version available: 0.4.1 -> 0.5.0
Loading Profile
Enter your encryption key
```

**To Reproduce**
1. Create a profile: `envio create dev_profile`
2. Add environment variable: `envio add dev_profile -e dummy=key`
3. Load profile: `envio load dev_profile`
4. Check setenv.sh. Line 8 has:
```bash
ENV_VARS=$(envio list -n dev_profile -v)
```
5. Create ENV_VARS by running: `ENV_VARS=$(envio list -n dev_profile -v)`
6.  `echo $ENV_VARS`
```bash
New version available: 0.4.1 -> 0.5.0
Loading Profile
Enter your encryption key
test=dev
```
7. Check the temp file created by setenv.sh (it's automatically deleted by the script so you need to edit it to not remove it)
```
export New version available: 0.4.1 -> 0.5.0
export Loading Profile
export Enter your encryption key
export dummy=key
```
The temp file is sourced to the shell and it produces error due to the unnecessary export lines.
8. Sourcing setenv.sh produces an errror:
```
❯ source  /home/marloeu/.envio/setenv.sh
> Enter your encryption key: ************
/tmp/tmp.oTZRrzyHPC:export:1: not valid in this context: available:
Failed to load environment variables from temp file

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```
**Expected behavior**
Temp file should only do `export dummy=key` .

**Device (please complete the following information):**
 - WSL2 (Ubuntu 23.10)
 - zsh
 - Version 0.4.1

**Additional context**
Looks like line `export New version available: 0.4.1 -> 0.5.0` is the main issue. `export Loading Profile` does not produce an issue.

**Comment by marloeuyjr** [comment]
Just to add that release 0.5.0 has 0.4.1 artifacts.

**Comment by humblepenguinn** [comment]
Thank you for opening this issue it helps out a lot! I changed the shell script up a bit and now it only accepts a specific pattern, essentially ignoring all the unnecessary lines you were seeing before. The artifacts have also been updated as well. 

I am closing this issue for now. Thank you once again!
