### ISSUE TITLE
Environment variable value cannot contain an equal sign

### ISSUE THREAD

**Issue by afh** [envio-cli/envio#33]
**Describe the bug**
Environment variable values are truncated to the first equal sign.

**To Reproduce**

1. Add an environment variable with a value that contains an equal sign:
`./target/debug/envio add -e foo=bar=baz test`
2. Print the environment variables from the profile to verify whether the environment variable value was added completely:
```sh
./target/debug/envio launch -p env test | grep ^foo`
> Enter your encryption key: ********
foo=bar
```

**Expected behavior**
The environment variable `foo` should have the value `bar=baz`

**Screenshots**
N/A ~~If applicable, add screenshots to help explain your problem.~~

**Device (please complete the following information):**
 - OS: macOS 14.3.1 (23D60)
 - Shell: zsh
 - CLI Version: 0.5.0

**Additional context**
The issue seems to stem from the use of [`split`](https://doc.rust-lang.org/std/primitive.str.html#method.split) in combination with [`next`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#tymethod.next). The [`Split.remainder`](https://doc.rust-lang.org/std/str/struct.Split.html#method.remainder) function seems to be well suited, unfortunately it is experimental API.
Possibly [`split_once`](https://doc.rust-lang.org/std/primitive.str.html#method.split_once) could be helpful to address this issue. Currently I understand too little about envio's codebase and Rust to propose a PR that addresses this issue.

**Comment by humblepenguinn** [comment]
I believe if you put `foo=bar=baz` inside quotes e.g `'foo=bar=baz'`,  envio will recognize the value properly.

However, as a user of the tool, if you believe using quotes seems a bit inconvinent, I'll take a look at `Split.remainder` API and the `split_once`  function and fix the issue.

Thank you for opening the issue. It helps out a lot

**Comment by afh** [comment]
My tests show no difference between using `foo=bar=baz` and `'foo=bar=baz'`, both only add `foo=bar`.

From a user perspective quotes shouldn't be necessary to set an environment variable whose value contains an equal sign:

```sh
% export foo=bar=baz
% print $foo
bar=baz
```

**Comment by afh** [comment]
I think there some more fine tuning would be beneficial, yet happy to address this over at #34 🙂
