### ISSUE TITLE
Feature: Launch command as positional argument

### ISSUE THREAD

**Issue by Rubensei** [envio-cli/envio#39]
**Feature**
Setting the command as an option seems a bit weird when the command itself is the main part of the `launch` subcommand. Having to set it as a string can also be a bit of a pain.

I think handling the command as positional argument with [`last`](https://docs.rs/clap/4.1.8/clap/builder/struct.Arg.html#method.last) would be way more friendly. It should also be less error prone since clap takes care of the whitespaces and won't allow an empty command.

```bash
envio launch my_profile --command "cmd arg1 arg2 ..."
envio launch my_profile -- cmd arg1 arg2 ...
```

**Compatibility**
Using `group` would allow supporting both option as well as making them mutually exclusive, avoiding the need for a breaking change or a different subcommand. This would require to bump clap version at least to [4.1.14](https://github.com/clap-rs/clap/blob/v4.5.1/CHANGELOG.md#4114---2023-03-28) but looking at the changelog it shouldn't be an issue since clap didn't change its MSRV until [4.4.0](https://github.com/clap-rs/clap/blob/v4.5.1/CHANGELOG.md#440---2023-08-24)

```rust
...
    #[command(
        name = "launch",
        about = "Run a command with the environment variables from a profile",
        override_usage = "envio launch <PROFILE_NAME> <--command COMMAND | -- COMMAND>"
    )]
    Launch {
        #[arg(required = true)]
        profile_name: String,
        #[command(flatten)]
        command: LaunchCommandArg,
    },
...

#[derive(clap::Args, Debug)]
#[group(required = true, multiple = false)]
pub struct LaunchCommandArg {
    #[arg(long = "command", short = 'c')]
    argument: Option<String>,
    #[arg(last = true, required = true)]
    positional: Vec<String>,
}
```

**Comment by humblepenguinn** [comment]
Hi @Rubensei this seems like a great idea. If this is something you would want to open a pull request for then go for it. Or else I would be glad to implement this myself.

Thank you!
