### ISSUE TITLE
envio requires rust 1.76.0

### ISSUE THREAD

**Issue by afh** [envio-cli/envio#43]
Rust 1.76.0 was released on February 8th, 2024 and envio bumped its minimum required Rust version to 1.76.0 on Feburary 17th, 2024. Unless envio requires 1.76.0 specific features—which I don't think it does as I was able to build it with Rust 1.75.0—I'd like to suggest to switch back to 1.75.0 if it doesn't cause any issues.

Being unfamiliar with the Rust ecosystem I'm unaware of any common or best practices in regards to requiring a specific Rust version, and am happy to hear reasons for using 1.76.0 over 1.75.0.

My main reason is that I don't know when Rust 1.76.0 will make it into nixpkgs and the 1.76.0 requirement would hinder updates to the envio package in nix until 1.76.0 lands. Maybe it's more of a nuisance for me at the moment than a real issue…

**Comment by humblepenguinn** [comment]
I see, well we can switch back to version `1.75.0`. The only reason I bumped the version was because Dependabot was constantly updating the packages, and those new package versions required new Rust versions, so I just decided to bump it to the latest Rust version.

**Comment by afh** [comment]
Thank you for considering. I'm also okay with changing Cargo.toml manually for development. But as I said earlier, I'm uncertain when support for Rust 1.76.0 will land in nixpkgs. Fortunately it is already being worked on (see [NixOS/nixpkgs#289940](https://github.com/NixOS/nixpkgs/pull/289940)) and might come sooner than I initially anticipated.

**Comment by afh** [comment]
ℹ️ Rust 1.76.0 has been [merged](https://github.com/NixOS/nixpkgs/pull/289940) to nixpkgs `staging`. It might make it even into the next release `24.05`.

**Comment by humblepenguinn** [comment]
> ℹ️ Rust 1.76.0 has been [merged](https://github.com/NixOS/nixpkgs/pull/289940) to nixpkgs `staging`. It might make it even into the next release `24.05`.

I don't know how nixpkg releases work. So do you think there is a need to fallback to version `1.75.0`? Or is it something `nix` users can wait out?

**Comment by afh** [comment]
My sincerest apologies, I've been inattentive in my last PR and also accidentally added the [1.75.0 changes to Cargo.toml](https://github.com/envio-cli/envio/blob/main/Cargo.toml#L4). To avoid back and forth changes my recommendation is to keep this as is it for now and update the lowest version that offers the functionality needed by the project.

**Comment by humblepenguinn** [comment]
Oh yeah, I forgot about that. I remember seeing it in the file changes. No worries. 

As you suggested, it's best we stick with `1.75.0` and only switch if needed.
