### ISSUE TITLE
Invalid setenv.sh generated

### ISSUE THREAD

**Issue by jerome-jutteau** [envio-cli/envio#48]
Hi there!

I started using envio for around 10 profiles and got this bug.

**Describe the bug**

Sometimes, calling `envio load` will alter setenv.sh in a way that the end of the file is invalid.
So when I reload my shell, an error pops out.

Example:
```bash
# file start skipped

    if [ $? -ne 0 ]; then
        echo "Failed to load environment variables from temp file"
        exit 1
    fi

    rm "$TMP_FILE"
fi
"
fi
```

**To Reproduce**
Steps to reproduce the behavior, without reloading my shell:
1. `envio unload`
2. `envio load xxxxxxxxxxxxx` 
3. `envio load yyyyyyyyyyyyyyyyyy`
4. `envio load xxxxxxxxxxxxx`
5. setenv.sh has now invalid content at the end (`"` and `fi`)

**Expected behavior**
envio does generate a valid script on each `load`

**Device (please complete the following information):**
 - OS: macOS 14.3.1 (23D60) on Apple M1 MacBook Air 2020
 - Shell: GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
 - CLI Version: 0.5.1

**Comment by jerome-jutteau** [comment]
This could be due to the fact that env names are different length and writing the file in [`create_shellscript`](https://github.com/envio-cli/envio/blob/303f64fd80d5ee7f32333c0386b17859447b85c0/src/lib.rs#L595) may leave an unwanted piece of text at the end. In that case, truncating the file before writing it could be the solution.

**Comment by humblepenguinn** [comment]
Thank you @jerome-jutteau for opening the issue and submitting a pull request for it! 

There seems to be a similar issue when exporting environment variables from a profile. I'll fix that
