### ISSUE TITLE
Remaining clear-text secrets in /tmp

### ISSUE THREAD

**Issue by jerome-jutteau** [envio-cli/envio#56]
Hi!

**Describe the bug**
`setenv.sh` [generates](https://github.com/envio-cli/envio/blob/ec72afb7c711941d69a0215f8f5572683127d980/src/lib.rs#L663) a tmp file (using `mktemp`), clear text secrets are written here, the file is then sourced and deleted.

For some unknown reason, I have cumulated some non-deleted tmp files containing clear-text secrets from my profiles.

**To Reproduce**

I am not sure how to reproduce this issue. This could occur as my shell is stopped or crash between `$TMP_FILE` writing and `rm "$TMP_FILE"`.

**Expected behavior**

Ideally, I would prefer that no file contains clear text secrets.

**Device (please complete the following information):**

 - OS: macOS 14.3.1 (23D60) on Apple M1 MacBook Air 2020
 - Shell: GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
 - CLI Version: 0.5.1

**Comment by jerome-jutteau** [comment]
Naively, one solution may be to make have `setenv.sh` run something like:
```bash
source "$(envio load --shell bash -n myprofile)"
```

**Comment by humblepenguinn** [comment]
@jerome-jutteau, I made a few changes to the shell script, so take a look and see if the issue still occurs for you.
