### ISSUE TITLE
Failed to unload env var in my windows.

### ISSUE THREAD

**Issue by ulic-youthlic** [envio-cli/envio#65]
**Describe the bug**
When I try to unload the profile, it fails. I tried to reload my shell, but the environment variables were still there.
the report is as following:

```
Reload your shell to apply changes
ERROR: Invalid syntax.
Type "REG DELETE /?" for usage.
```

**To Reproduce**
1. Create a profile. `envio create lab -g select`
2. add env var. `envio add lab -e WEB_ADDRESS="127.0.0.1:8080"`
3. load it. `envio load lab`
4. unload it. `envio unload lab`
5. restart my terminal.
6. echo the env var. `echo $Env:WEB_ADDRESS`

**Expected behavior**
The environment variable `WEB_ADDRESS` remains after unloading the profile.

**Screenshots**
![image](https://github.com/envio-cli/envio/assets/121918198/149c3e94-f2a8-40a2-9ad6-cec0c96c75cd)
![image](https://github.com/envio-cli/envio/assets/121918198/8fe68143-a50f-498a-a139-064d07779453)

**Device (please complete the following information):**
 - OS: windows11 23H2
 - Shell: powershell 7.4.2
 - CLI Version: 0.5.1 (installed directly from `cargo install`)

**Additional context**
I can still find WEB_ADDRESS in the registry.

**Comment by humblepenguinn** [comment]
@ulic-youthlic, I've just pushed a commit that should resolve the issue. Test it out and let me know

**Comment by ulic-youthlic** [comment]
I cloned this repository and then installed it using `cargo install --path .`. Now, I have good news and bad news:
It works, but not completely (maybe).

------

Here’s the process I followed:
1. Created a profile named "test"
2. Added an environment variable `Port=2333`
3. Loaded this profile
4. Printed the environment variable directly, no response
5. Restarted my terminal
6. Printed `Port`, output was 2333
7. Unloaded the profile, output was successful
8. Printed `Port`, output was 2333
9. Restarted the terminal
10. Printed `Port`, output was 2333
11. Restarted the computer
12. Printed `Port`, no output

------

Yes, the latest envio can indeed correctly delete environment variables, but the problem is that Windows seems to be a bit slow to react and requires a computer restart to properly update the environment variables. Anyway, thanks for all you've done.
