### ISSUE TITLE
env files encrypted with gpg and created with version 0.5.1 cannot be read with version 0.6.

### ISSUE THREAD

**Issue by afh** [envio-cli/envio#67]
**Describe the bug**
When using e gpg encrypted env file that was created with version 0.5.1,
envio 0.6.1 prompts for the encryption password instead of using the gpg key.

**To Reproduce**
1. Build version 0.5.1 and 0.6.0 of envio
2. Using version 0.5.1
3. envio create mwe -g $GPGID
4. envio add mwe --envs test
5. envio launch mwe --command /usr/bin/env | grep test
6. Using version 0.6.0
7. envio launch mwe -- /usr/bin/env | grep test
8. envio prompts for the encryption key instead of using the gpg key the profile was created with.

**Expected behavior**
envio version 0.6.0 launches the /usr/bin/env utility with an environment that is enriched with the environment variable `test` from the `mwe` profile.

**Screenshots**

**Device (please complete the following information):**
 - OS: macOS 15.0 (24A335)
 - Shell zsh
 - CLI Version 0.5.1 and 0.6.0

**Additional context**

**Comment by afh** [comment]
Another thing I noticed is that when using `gpg -d` to decrypt a gpg encrypted profile, the following error message appears:

```
[don't know]: invalid packet (ctb=2d)
gpg: [don't know]: invalid packet (ctb=2d)
```

I assume this is caused by the `-----GPG ENCRYPTED FILE-----`-suffix that is added to the encrypted profile file

**Comment by humblepenguinn** [comment]
implemented a fix, let me know if it works now for you

**Comment by humblepenguinn** [comment]
> Another thing I noticed is that when using `gpg -d` to decrypt a gpg encrypted profile, the following error message appears:
> 
> ```
> gpg: [don't know]: invalid packet (ctb=2d)
> gpg: [don't know]: invalid packet (ctb=2d)
> ```
> 
> I assume this is caused by the `-----GPG ENCRYPTED FILE-----`-suffix that is added to the encrypted profile file

Yes profiles are not meant to be decrypted manually. It's something `envio` handles for you

**Comment by afh** [comment]
Yes, that works, @humblepenguinn, thanks.

What is the motivation to use a custom identifier within the env file to distinguish between gpg and age encrypted files, instead of using the encryption scheme as another file suffix on the the profile files, e.g. `gpg-encryptedprofile.env.gpg` and `age-encrypted.env.age`?

**Comment by humblepenguinn** [comment]
> Yes, that works, @humblepenguinn, thanks.
> 
> What is the motivation to use a custom identifier within the env file to distinguish between gpg and age encrypted files, instead of using the encryption scheme as another file suffix on the the profile files, e.g. `gpg-encryptedprofile.env.gpg` and `age-encrypted.env.age`?

I thought it would look weird to have the encryption type alongside the file name and also didn't see any potential benefits in that approach.

So I just used a custom identifier since it helped maintain consistency in the extensions of the profile files.

**Comment by afh** [comment]
I see, thanks for the added context.
Personally I would have taken a different appraoch as I think there is value in being able to interact with the encrypted env files via other means (e.g. editors that can edit encrypted files) than envio.

**Comment by humblepenguinn** [comment]
I understand, but even if the file extension approach is used, it wouldn’t help much with editors that can modify encrypted files, as the encrypted data is simply a serialized form of the profile struct. Additionally, I believe it's better if users avoid editing their profiles with such editors, as it could result in `envio` being unable to decrypt and load the profiles properly.

**Comment by afh** [comment]
I see, the decrypted file appeared readable and I assumed there was nothing special going on there, but if it's a serialisation that's another story.
Having it serialise to a human editable format might be nice to have…

**Comment by humblepenguinn** [comment]
Maybe this is something we can look into for future releases. Doesn't seem like a bad idea
